#define PREFIX "usahime_"
#define RGSSX_FORWARD(yield)\
	yield(EncDefaultCharEncoding)\
	yield(RGSSAddRTPPath)\
	yield(RGSSAudioFinalize)\
	yield(RGSSAudioInitialize)\
	yield(RGSSClearRTPPath)\
	yield(RGSSErrorMessage)\
	yield(RGSSErrorType)\
	yield(RGSSEval)\
	yield(RGSSFinalize)\
	yield(RGSSGC)\
	yield(RGSSGameMain)\
	yield(RGSSGetBool)\
	yield(RGSSGetDouble)\
	yield(RGSSGetInt)\
	yield(RGSSGetPathWithRTP)\
	yield(RGSSGetRTPPath)\
	yield(RGSSGetStringACP)\
	yield(RGSSGetStringUTF8)\
	yield(RGSSGetStringUTF16)\
	yield(RGSSGetTable)\
	yield(RGSSSetString)\
	yield(RGSSSetStringACP)\
	yield(RGSSSetStringUTF16)\
	yield(RGSSSetStringUTF8)\
	yield(RGSSGetSymbol)\
	yield(RGSSSetupRTP)\
	yield(RegDefaultSyntax)\
	yield(RegEncodingASCII)\
	yield(RegEncodingEUC_JP)\
	yield(RegEncodingSJIS)\
	yield(RegEncodingUTF8)\
	yield(RegSyntaxRuby)\
	yield(enc_get_left_adjust_char_head)\
	yield(enc_get_prev_char_head)\
	yield(enc_get_right_adjust_char_head)\
	yield(re_alloc_pattern)\
	yield(regex_end)\
	yield(regex_error_code_to_str)\
	yield(regex_foreach_name)\
	yield(regex_free)\
	yield(regex_get_encoding)\
	yield(regex_get_options)\
	yield(regex_get_syntax)\
	yield(regex_init)\
	yield(regex_match)\
	yield(regex_name_to_backref_number)\
	yield(regex_name_to_group_numbers)\
	yield(regex_new)\
	yield(regex_number_of_names)\
	yield(regex_recompile)\
	yield(regex_region_clear)\
	yield(regex_region_copy)\
	yield(regex_region_free)\
	yield(regex_region_new)\
	yield(regex_region_resize)\
	yield(regex_search)\
	yield(regex_set_verb_warn_func)\
	yield(regex_set_warn_func)\
	yield(regex_version)\
	yield(ruby_re_adjust_startpos)\
	yield(ruby_re_compile_pattern)\
	yield(ruby_re_free_pattern)\
	yield(ruby_re_free_registers)\
	yield(ruby_re_match)\
	yield(ruby_re_mbcinit)\
	yield(ruby_re_recompile_pattern)\
	yield(ruby_re_search)\
	yield(ruby_re_set_casetable)\
	yield(RGSSInitialize)\
	yield(RGSSInitialize2)\
  yield(RGSSInitialize3)\
  yield(RGSSInitialize4)\
  yield(RGSSInitialize5)\
  yield(RGSSInitialize6)\
  yield(RGSSInitialize7)\
  yield(RGSSInitialize8)\
  yield(RGSSInitialize9)\
  yield(RGSSInitializeA)\
  yield(RGSSSetupFonts)\
   

